menu:
- {name: 'startups', url: '/startups'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/pabair'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/patrickbaier/'}

contacts:
- {name: 'Dr. Patrick Baier', title: 'Professor', department: 'Computer Science ', institution: 'Hochschule Karlsruhe', institution_address: 'Moltkestraße 30, 76133 Karlsruhe', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
